# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gosimports < Formula
  desc "Command gosimports updates your Go import lines, adding missing ones, removing unreferenced ones, and removing redundant blank lines."
  homepage "https://pkg.go.dev/github.com/rinchsan/gosimports/cmd/gosimports"
  version "0.1.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rinchsan/gosimports/releases/download/v0.1.5/gosimports_0.1.5_darwin_arm64.tar.gz"
      sha256 "5dcb01c6ee8ce359db7f9a2f1a0794017088497675c8c868632785878ec7c0e0"

      def install
        bin.install "gosimports"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rinchsan/gosimports/releases/download/v0.1.5/gosimports_0.1.5_darwin_amd64.tar.gz"
      sha256 "57608587e404a6339ea4cc1ed2b47357198a749350635bc8e572009056ef1aa9"

      def install
        bin.install "gosimports"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rinchsan/gosimports/releases/download/v0.1.5/gosimports_0.1.5_linux_arm64.tar.gz"
      sha256 "80d069a103033d0a5c7e56e926d5453aa0666088ab4605707e9286c7d4357478"

      def install
        bin.install "gosimports"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rinchsan/gosimports/releases/download/v0.1.5/gosimports_0.1.5_linux_amd64.tar.gz"
      sha256 "c82b36db12ed861bcd68126b4c0fd122e2291f2200ea230c0ad5a438923a8e76"

      def install
        bin.install "gosimports"
      end
    end
  end

  test do
    system "#{bin}/gosimports --help"
  end
end
