# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Groupvar < Formula
  desc "Command groupvar finds low-readability variable/constant declarations."
  homepage "https://pkg.go.dev/github.com/rinchsan/groupvar/cmd/groupvar"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rinchsan/groupvar/releases/download/v0.1.0/groupvar_0.1.0_darwin_amd64.tar.gz"
      sha256 "fc93b416de0da6cc01d0c633628a085ef46293c7d777f93c8ad8a51f10ed8580"

      def install
        bin.install "groupvar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rinchsan/groupvar/releases/download/v0.1.0/groupvar_0.1.0_darwin_arm64.tar.gz"
      sha256 "320501afe7a6fb384774ab9292c2db3edaa1f27324229732b90682c9187caf95"

      def install
        bin.install "groupvar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rinchsan/groupvar/releases/download/v0.1.0/groupvar_0.1.0_linux_arm64.tar.gz"
      sha256 "15031b951ef60833144e7385457c541eac5c489d68ed74e1daa47f43ab1e16c7"

      def install
        bin.install "groupvar"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rinchsan/groupvar/releases/download/v0.1.0/groupvar_0.1.0_linux_amd64.tar.gz"
      sha256 "07699242d3234703070cbe80664b2e697db901da00d19d4b545052f95297564a"

      def install
        bin.install "groupvar"
      end
    end
  end

  test do
    system "#{bin}/groupvar --help"
  end
end
